-- ============================================================
-- BTA LAB Services page Georgian content fixes
-- Adds missing add-on services and corrects Georgian category wording.
-- ============================================================

update public.portfolio_categories
set name_ka = 'ონლაინ მაღაზია'
where name = 'E-commerce';

update public.portfolio_projects
set category_label_ka = 'ონლაინ მაღაზია'
where category = 'E-commerce';

update public.site_content
set value_ka = replace(value_ka, 'ელ-' || 'კომერცია', 'ონლაინ მაღაზია')
where value_ka like '%' || 'ელ-' || 'კომერცია' || '%';

insert into public.service_packages (
  id,
  section,
  name,
  name_ka,
  name_en,
  price,
  billing_label,
  billing_label_ka,
  billing_label_en,
  description,
  description_ka,
  description_en,
  ideal_for,
  ideal_for_ka,
  ideal_for_en,
  features,
  features_ka,
  features_en,
  delivery_time,
  delivery_time_ka,
  delivery_time_en,
  cta,
  cta_ka,
  cta_en,
  cta_label_ka,
  cta_label_en,
  highlighted,
  custom_price,
  price_explanation,
  price_explanation_ka,
  price_explanation_en,
  icon_name,
  display_order,
  published
)
values
  (
    '47ec467a-96ee-49af-9189-10bfdf76f45c',
    'addons',
    'SEO Optimization',
    'SEO ოპტიმიზაცია',
    'SEO Optimization',
    '199 ₾-დან',
    '',
    '',
    '',
    'Technical and search engine optimization for your website.',
    'ვებგვერდის ტექნიკური და საძიებო სისტემებისთვის ოპტიმიზაცია.',
    'Technical and search engine optimization for your website.',
    '',
    '',
    '',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '',
    '',
    '',
    'Choose Add-on',
    'სერვისის არჩევა',
    'Choose Add-on',
    'სერვისის არჩევა',
    'Choose Add-on',
    false,
    false,
    '',
    '',
    '',
    'Search',
    0,
    true
  ),
  (
    '03f6dca0-7886-44e5-96fd-c42f5e7ebd62',
    'addons',
    'Google Business Profile Setup',
    'Google Business პროფილის შექმნა',
    'Google Business Profile Setup',
    '99 ₾',
    '',
    '',
    '',
    'Create and optimize your business presence on Google Maps and Search.',
    'თქვენი ბიზნესის სწორად შექმნა და ოპტიმიზაცია Google Maps-სა და Google Search-ში.',
    'Create and optimize your business presence on Google Maps and Search.',
    '',
    '',
    '',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '',
    '',
    '',
    'Choose Add-on',
    'სერვისის არჩევა',
    'Choose Add-on',
    'სერვისის არჩევა',
    'Choose Add-on',
    false,
    false,
    '',
    '',
    '',
    'MapPin',
    1,
    true
  ),
  (
    '24c13235-ee57-46a9-bf8b-303521a15e2b',
    'addons',
    'Google Analytics + Search Console',
    'Google Analytics + Search Console',
    'Google Analytics + Search Console',
    '79 ₾',
    '',
    '',
    '',
    'Set up tracking for visitors, search performance, and user behavior.',
    'ვიზიტორების ანალიტიკის, ძიების შედეგებისა და მომხმარებლის ქცევის მონიტორინგის სისტემების გამართვა.',
    'Set up tracking for visitors, search performance, and user behavior.',
    '',
    '',
    '',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '',
    '',
    '',
    'Choose Add-on',
    'სერვისის არჩევა',
    'Choose Add-on',
    'სერვისის არჩევა',
    'Choose Add-on',
    false,
    false,
    '',
    '',
    '',
    'BarChart3',
    2,
    true
  ),
  (
    '09e3cbd8-64df-4327-ae19-4dbc47c82afa',
    'addons',
    'Business Email Setup',
    'ბიზნეს ელფოსტის გამართვა',
    'Business Email Setup',
    '49 ₾',
    '',
    '',
    '',
    'Professional email setup using your own domain.',
    'პროფესიონალური ელფოსტის შექმნა თქვენი საკუთარი დომენით.',
    'Professional email setup using your own domain.',
    'info@yourbusiness.ge',
    'info@yourbusiness.ge',
    'info@yourbusiness.ge',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '',
    '',
    '',
    'Choose Add-on',
    'სერვისის არჩევა',
    'Choose Add-on',
    'სერვისის არჩევა',
    'Choose Add-on',
    false,
    false,
    '',
    '',
    '',
    'Mail',
    3,
    true
  ),
  (
    '08ae5842-1db8-4671-be8a-37685cc962cd',
    'addons',
    'Domain & Hosting Setup',
    'დომენისა და ჰოსტინგის გამართვა',
    'Domain & Hosting Setup',
    '49 ₾',
    '',
    '',
    '',
    'Connect your domain, configure hosting, and publish your site.',
    'დომენის დაკავშირება, ჰოსტინგის გამართვა და ვებგვერდის განთავსება.',
    'Connect your domain, configure hosting, and publish your site.',
    '',
    '',
    '',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '',
    '',
    '',
    'Choose Add-on',
    'სერვისის არჩევა',
    'Choose Add-on',
    'სერვისის არჩევა',
    'Choose Add-on',
    false,
    false,
    '',
    '',
    '',
    'Globe',
    4,
    true
  )
on conflict (id) do update
set
  section = excluded.section,
  name = excluded.name,
  name_ka = excluded.name_ka,
  name_en = excluded.name_en,
  price = excluded.price,
  billing_label = excluded.billing_label,
  billing_label_ka = excluded.billing_label_ka,
  billing_label_en = excluded.billing_label_en,
  description = excluded.description,
  description_ka = excluded.description_ka,
  description_en = excluded.description_en,
  ideal_for = excluded.ideal_for,
  ideal_for_ka = excluded.ideal_for_ka,
  ideal_for_en = excluded.ideal_for_en,
  features = excluded.features,
  features_ka = excluded.features_ka,
  features_en = excluded.features_en,
  delivery_time = excluded.delivery_time,
  delivery_time_ka = excluded.delivery_time_ka,
  delivery_time_en = excluded.delivery_time_en,
  cta = excluded.cta,
  cta_ka = excluded.cta_ka,
  cta_en = excluded.cta_en,
  cta_label_ka = excluded.cta_label_ka,
  cta_label_en = excluded.cta_label_en,
  highlighted = excluded.highlighted,
  custom_price = excluded.custom_price,
  price_explanation = excluded.price_explanation,
  price_explanation_ka = excluded.price_explanation_ka,
  price_explanation_en = excluded.price_explanation_en,
  icon_name = excluded.icon_name,
  display_order = excluded.display_order,
  published = excluded.published;
